main:
    -   identifier: home
        name: Home
        url: 
        weight: 100
    -   identifier: services
        name: Services
        url: 
        weight: 200
    -   identifier: about
        name: About
        url: /about
        weight: 300
    -   identifier: blog
        name: Blogs
        url: /blog
        weight: 400
footer: 
    -   identifier: privacy
        name: Privacy policy
        url: /privacy-policy
        weight: 100
    -   identifier: terms
        name: Terms & conditions
        url: /terms-and-conditions
        weight: 200