favicon: images/logo-simple.png
logo: images/logo.png
logo_width: "300px"
logo_text: "ADSCIAN" #if logo is missing
image: images/logo.png
variables:
  white: "#ffffff"
  black: "#324a51"
  light: "#FAFAFA"
  primary_color: "#06a6a1"
preloader:
  enable: true
  preloader: "images/logo_notext.png"


footer_info: >-
  AD Scientific Consulting & Environmental Systems Analytics
  (ADSCIAN SRL)
contact_form_action: 'https://formspree.io/f/xgernlzd'
copyright: >-
  Designed By [Themefisher](https://themefisher.com/) & Developed By
  [Gethugothemes](https://gethugothemes.com/)
custom_script: ''
buy_premium_popup: true
mainSections:
  - blog
reading_time: true
contact_info:
  address: '2118 Thornridge Cir. Syracuse, Connecticut 35624'
  phone:
    - +704-555-0127
    - +205-857-2321
    - +002-569-6969
  email:
    - info@andromeda.io
    - smith@anderson.io
    - john@anderson.io
imaging:
  quality: 100

navigation_button:
  enable: false
  label: Buy Premium
  link: 'https://gethugothemes.com/products/andromeda/'

cookies:
  enable: false
  expire_days: 2
  content: >-
    This site uses cookies. By continuing to use this website, you agree to
    their use.
  button: I Accept

cta:
  enable: false
  title: Get Andromeda-Premium Now
  content: >-
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br>
    Werat viverra id et aliquet. vulputate egestas sollicitudin.
  button: Download The Theme
  button_link: 'https://gethugothemes.com/products/andromeda/'
social:
  - title: Andromeda
    icon: lab la-facebook-f
    link: '#!'
  - title: AndromedaTweet
    icon: lab la-twitter
    link: '#!'
  - title: AndromedaIn
    icon: lab la-linkedin-in
    link: '#!'
  - title: AndromedaPin
    icon: lab la-pinterest
    link: '#!'
