favicon: images/favicon.png
logo: images/logo.svg
logo_width: "300px"
logo_text: "ADSCIAN" #if logo is missing
image: images/logo.png
variables:
  white: "#ffffff"
  black: "#324a51"
  light: "#DBF0E9"
  primary_color: "#06a6a1"
preloader:
  enable: true
  preloader: "images/logo_32px.png"

  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/line-awesome/css/line-awesome.min.css
      - link: plugins/swiper/swiper-bundle.min.css
      - link: plugins/aos/aos.css
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/aos/aos.js
      - link: plugins/swiper/swiper-bundle.min.js
      - link: plugins/rellax/rellax.min.js
      - link: plugins/webfont-loader/webfont-loader-2.min.js

footer_info:
  name: "ADSCIAN"
  fullname: "AD Scientific Consulting & Environmental Systems Analytics (ADSCIAN SRL)"
  email: "contact@adscian.be"
  address: "Av. du Paepedelle 65, 1160, Brussels, Belgium"
  phone: "+ 32 492 10 49 68"

imaging:
  quality: 100

navigation_button:
  enable: false
  label: Buy Premium
  link: 'https://gethugothemes.com/products/andromeda/'

cookies:
  enable: false
  expire_days: 2
  content: >-
    This site uses cookies. By continuing to use this website, you agree to
    their use.
  button: I Accept

cta:
  enable: false
  title: Get Andromeda-Premium Now
  content: >-
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br>
    Werat viverra id et aliquet. vulputate egestas sollicitudin.
  button: Download The Theme
  button_link: 'https://gethugothemes.com/products/andromeda/'

social:
  - title: AdscianIn
    icon: lab la-linkedin-in
    link: 'https://www.linkedin.com/company/adscian'

