################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Conçu Par [Themefisher](https://themefisher.com/) & Développé Par [Gethugothemes](https://gethugothemes.com/)"

################################### Dutch language #####################################
[nl]
languageName = "Nl"
languageCode = "nl-nl"
contentDir = "content/dutch"
weight = 2
# copyright
copyright = "Ontworpen door [Themefisher](https://themefisher.com/) & Ontwikkeld door [Gethugothemes](https://gethugothemes.com/)"
