############# Dutch navigation ##############

# main menu
[[main]]
identifier = "home"
name = "Home"
url = ""
weight = 100

[[main]]
identifier = "sevices"
name = "Diensten"
url = "#services"
weight = 200

[[main]]
identifier = "about"
name = "Over ons"
url = "#about"
weight = 300

[[main]]
identifier = "contact"
name = "Contact"
url = "#contact"
weight = 400

[[footer]]
identifier = "legal"
name = "Juridische informatie"
url = "/legal"
weight = 100
