#################### default parameters ################################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "300px"
# if logo_webp set false, it will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "ADSCIAN"

# footer information
[footer_info]
name = "ADSCIAN"
fullname = "AD Scientific Consulting & Environmental Systems Analytics (ADSCIAN SRL)"
email = "contact@adscian.be"
address = "Av. du Paepedelle 65, 1160, Brussels, Belgium"
phone = "+ 32 492 10 49 68"

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# Main Sections
mainSections = ["blog"]

# contact information
[contact_info]
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
email = ["info@andromeda.io", "smith@anderson.io", "john@anderson.io"]

# Preloader
# module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Sign Up Now"
link = "signup/"

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["environmental consulting", "climate change solutions",
  "water resource management", "data science for environment",
  "scientific research synthesis", "GIS and data analysis training",
  "proposal writing for environmental projects", "hydrology consulting",
  "public sector environmental support", "scientific literature review"
]
description = """ADSCIAN offers expert consulting in water, environment, and
climate challenges. We bridge science and action through data analysis,
research synthesis, and tailored training for public, private, and academic
sectors."""
author = "ADSCIAN"
image = "images/og-adscian.png" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
# matomo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/matomo-analytics
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
# baidu module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/baidu-analytics
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# plausible module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/plausible-analytics
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# counter module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/counter-analytics
[counter]
enable = false
username = "" # your username

# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# crisp chat - module: https://github.com/gethugothemes/hugo-modules/tree/master/components/crisp-chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = false
title = "Helping teams in the world with focus"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"
button_link = "/"

[[social]]
title = "AdscianIn"
icon = "lab la-linkedin-in"
link = "https://www.linkedin.com/company/adscian"

[[social]]
title = "GitHub"
icon = "lab la-github"
link = "https://github.com/adscian"
